window.DESIGNER_TYPE_TEST = {
  scale: [
    { value: 1, label: "Strongly disagree" },
    { value: 2, label: "Disagree" },
    { value: 3, label: "Neutral" },
    { value: 4, label: "Agree" },
    { value: 5, label: "Strongly agree" },
  ],
  dimensions: [
    { id: "strategy", name: "Strategic product framing", summary: "Connecting user needs, constraints, scope, and outcomes." },
    { id: "experienceDesign", name: "Experience design and interaction craft", summary: "Structuring flows, information, states, feedback, and behavior." },
    { id: "research", name: "Research and evidence orientation", summary: "Learning from users, reducing bias, and synthesizing evidence." },
    { id: "systems", name: "Systems and consistency thinking", summary: "Reusable patterns, standards, tokens, documentation, and accessibility." },
    { id: "build", name: "Technical implementation and prototyping", summary: "Working in code, feasibility, and design-to-build quality." },
    { id: "humanFactors", name: "Human factors and risk sensitivity", summary: "Understanding users, environments, safety, ergonomics, and error prevention." },
    { id: "content", name: "Content clarity and narrative design", summary: "Designing with words, naming, microcopy, and content standards." },
  ],
  types: [
    {
      id: "product",
      name: "Product Designer",
      color: "#d29b2f",
      summary: "You like connecting user needs, product direction, constraints, and interface quality into one coherent decision path.",
      strengths: ["Problem framing", "Scoping and tradeoffs", "Cross-functional decision making", "End-to-end product thinking"],
      projectIdeas: [
        "Redesign a campus workflow and justify what changed and why",
        "Create an MVP feature concept with user problem, scope, flows, and success signals",
        "Compare two product directions and defend a recommendation",
      ],
      skillsToBuild: ["Product thinking and prioritization", "Journey mapping", "Usability testing basics", "Clear design rationale and presentation"],
      rolesToExplore: ["Product Designer", "Associate Product Designer", "Growth Designer", "Product-minded UX Designer"],
      priorityDimensions: ["strategy", "research", "experienceDesign"],
      recruitingCompanies: [
        { name: "Meta", url: "https://www.metacareers.com/", logo: "assets/company-logos/META.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Abbott", url: "https://www.jobs.abbott/", logo: "assets/company-logos/ABT.png" },
      ],
      additionalCompanies: ["Airbnb", "Intuit", "Art of Problem Solving"],
    },
    {
      id: "ux",
      name: "UX Designer",
      color: "#2f9c95",
      summary: "You are most energized by making tasks understandable, flows usable, and navigation clearer for real people.",
      strengths: ["Flow design", "Information architecture", "Usability improvement", "Wireframing and iteration"],
      projectIdeas: [
        "Untangle a confusing multi-step student flow",
        "Redesign a dense dashboard for clarity and task completion",
        "Run a lightweight usability test on a campus or club tool",
      ],
      skillsToBuild: ["Information architecture", "Wireframing and prototyping", "Usability heuristics", "Accessibility basics"],
      rolesToExplore: ["UX Designer", "Experience Designer", "Product Designer with UX emphasis", "Service Designer intern"],
      priorityDimensions: ["experienceDesign", "research", "content"],
      recruitingCompanies: [
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
      ],
      additionalCompanies: ["Intuit", "ServiceNow", "Salesforce"],
    },
    {
      id: "interaction",
      name: "Interaction Designer",
      color: "#1f7ae0",
      summary: "You care about what the interface does moment to moment: states, feedback, timing, transitions, and behavioral clarity.",
      strengths: ["Interaction detail", "State modeling", "Microinteractions", "High-fidelity prototyping"],
      projectIdeas: [
        "Prototype a small but polished interaction with loading, hover, focus, error, and success states",
        "Design a set of onboarding interactions and explain the behavior rules",
        "Create a motion or transition spec for a mobile flow",
      ],
      skillsToBuild: ["State diagrams and interaction specs", "Advanced prototyping", "Motion and feedback principles", "Front-end fundamentals for implementation-aware design"],
      rolesToExplore: ["Interaction Designer", "Product Designer with interaction focus", "Prototype Designer", "Motion or interaction-focused UX role"],
      priorityDimensions: ["experienceDesign", "build", "systems"],
      recruitingCompanies: [
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Figma", url: "https://www.figma.com/careers/", logo: "assets/company-logos/FIG.png" },
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
      ],
      additionalCompanies: ["Apple", "Airbnb", "Duolingo"],
    },
    {
      id: "research",
      name: "UX Researcher",
      color: "#3b79b7",
      summary: "You are motivated by evidence, interviews, synthesis, and helping teams make better decisions under uncertainty.",
      strengths: ["Study planning", "Interviewing and observation", "Insight synthesis", "Evidence-based communication"],
      projectIdeas: [
        "Run a usability study on a student app and synthesize findings",
        "Conduct interviews about how students plan coursework or internships",
        "Compare survey and interview results on a design question",
      ],
      skillsToBuild: ["Moderated interviewing", "Study design and bias reduction", "Affinity mapping and synthesis", "Basic quantitative reasoning"],
      rolesToExplore: ["UX Researcher", "Research Assistant in HCI or CogSci", "Product Research Intern", "Design Researcher"],
      priorityDimensions: ["research", "humanFactors", "strategy"],
      recruitingCompanies: [
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
      ],
      additionalCompanies: ["Meta", "Spotify", "Intuit"],
    },
    {
      id: "systems",
      name: "Design Systems Designer",
      color: "#7c5cbf",
      summary: "You like creating reusable patterns, shared standards, and accessible consistency that scale across many screens and teams.",
      strengths: ["Pattern recognition", "Reusable component thinking", "Documentation and governance", "Accessibility-minded consistency"],
      projectIdeas: [
        "Create a mini design system for a club or campus app",
        "Audit an interface for inconsistency and propose reusable fixes",
        "Document a component library with usage rules and accessibility notes",
      ],
      skillsToBuild: ["Component anatomy and tokens", "Figma libraries and variants", "Documentation and adoption strategy", "Accessibility and standards"],
      rolesToExplore: ["Design Systems Designer", "Systems-focused Product Designer", "UI Systems Designer", "DesignOps-adjacent systems role"],
      priorityDimensions: ["systems", "build", "content"],
      recruitingCompanies: [
        { name: "Figma", url: "https://www.figma.com/careers/", logo: "assets/company-logos/FIG.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
      ],
      additionalCompanies: ["Salesforce", "Atlassian", "Shopify", "IBM"],
    },
    {
      id: "technology",
      name: "Design Technologist / UI Engineer",
      color: "#55a66f",
      summary: "You want to turn ideas into working interfaces, prove feasibility in code, and keep design quality intact during implementation.",
      strengths: ["Code-based prototyping", "Engineering collaboration", "Technical feasibility judgment", "Implementation quality"],
      projectIdeas: [
        "Build a coded prototype with real states and data",
        "Create an accessible reusable component in HTML/CSS/JS or React",
        "Turn a Figma concept into a responsive front-end demo",
      ],
      skillsToBuild: ["HTML, CSS, and JavaScript", "Component-based front-end development", "Accessibility in code", "Browser devtools and implementation debugging"],
      rolesToExplore: ["Design Technologist", "UX Engineer", "UI Engineer", "Design Engineer", "Front-end prototyper"],
      priorityDimensions: ["build", "experienceDesign", "systems"],
      recruitingCompanies: [
        { name: "Amazon", url: "https://www.amazon.jobs/", logo: "assets/company-logos/AMZN.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
        { name: "Booz Allen", url: "https://careers.boozallen.com/", logo: "assets/company-logos/BAH.png" },
      ],
      additionalCompanies: ["IMDb", "Airbnb", "Vercel"],
    },
    {
      id: "humanFactors",
      name: "Human Factors Engineer",
      color: "#c85d3a",
      summary: "You are drawn to systems where safety, error prevention, ergonomics, and real-world context matter as much as visual polish.",
      strengths: ["Task and context analysis", "Risk and error prevention", "Evaluation in realistic conditions", "Human performance thinking"],
      projectIdeas: [
        "Analyze a high-stakes check-in or scheduling flow for error risks and recovery",
        "Redesign a kiosk, device workflow, or public-service experience for safer use",
        "Create a usability validation plan for a complex tool or device companion app",
      ],
      skillsToBuild: ["Task analysis and use scenarios", "Risk analysis and error taxonomy", "Usability validation methods", "Accessibility and ergonomics literacy"],
      rolesToExplore: ["Human Factors Engineer", "Usability Engineer", "Ergonomist", "Human-Systems Integration role", "Safety-critical UX role"],
      priorityDimensions: ["humanFactors", "research", "systems"],
      recruitingCompanies: [
        { name: "Illumina", url: "https://www.illumina.com/company/careers.html", logo: "assets/company-logos/ILMN.png" },
        { name: "Sony", url: "https://www.sony.com/en/SonyInfo/Careers/", logo: "assets/company-logos/SONY.png" },
        { name: "Becton Dickinson", url: "https://jobs.bd.com/", logo: "assets/company-logos/BDX.png" },
      ],
      additionalCompanies: ["Dexcom", "Medtronic", "Abbott"],
    },
    {
      id: "content",
      name: "UX Writer / Content Designer",
      color: "#cc4f8b",
      summary: "You think design quality depends on the words as much as the screens, and you care about clarity, naming, tone, and content systems.",
      strengths: ["Microcopy and naming", "Clarity and tone", "Content patterns and standards", "Cross-team language consistency"],
      projectIdeas: [
        "Rewrite onboarding and error copy for a real app concept",
        "Create naming and microcopy rules for a component set",
        "Run a content-focused usability test on instructions or form errors",
      ],
      skillsToBuild: ["UX writing and microcopy", "Voice and tone systems", "Content testing", "Structured content and design collaboration"],
      rolesToExplore: ["UX Writer", "Content Designer", "Product Content Strategist", "Conversation-design adjacent role"],
      priorityDimensions: ["content", "experienceDesign", "research"],
      recruitingCompanies: [
        { name: "Figma", url: "https://www.figma.com/careers/", logo: "assets/company-logos/FIG.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Meta", url: "https://www.metacareers.com/", logo: "assets/company-logos/META.png" },
      ],
      additionalCompanies: ["Airbnb", "Intuit", "Notion"],
    },
  ],
  questions: [
    { id: "q01", prompt: "For a client checkpoint, I would rather show a polished clickable prototype than a rough concept with richer discussion notes.", dimension: "strategy", reverse: false, weights: { product: 2, ux: -2, interaction: 3, research: -3, systems: 0, technology: 3, humanFactors: -1, content: -1 } },
    { id: "q02", prompt: "I would delay high-fidelity polish if the team has not agreed on the user problem, constraints, and success criteria.", dimension: "strategy", reverse: false, weights: { product: 2, ux: 2, interaction: -2, research: 2, systems: 0, technology: -2, humanFactors: 1, content: 1 } },
    { id: "q03", prompt: "When time is short, a believable happy-path demo is more useful than exploring edge cases that probably will not appear in the presentation.", dimension: "strategy", reverse: false, weights: { product: 3, ux: -1, interaction: 2, research: -2, systems: -2, technology: 2, humanFactors: -3, content: 0 } },
    { id: "q04", prompt: "Before making anything high fidelity, I want to map stakeholder priorities, constraints, and what each group needs to feel heard.", dimension: "strategy", reverse: false, weights: { product: 1, ux: 1, interaction: -1, research: 2, systems: 0, technology: -2, humanFactors: 1, content: 2 } },
    { id: "q05", prompt: "I would rather define the success metric and MVP scope than spend that same time fine-tuning individual microinteractions.", dimension: "strategy", reverse: false, weights: { product: 3, ux: 0, interaction: -3, research: 1, systems: 0, technology: -1, humanFactors: 0, content: 0 } },
    { id: "q06", prompt: "If I only had one afternoon, I would rather run a rough usability discussion than make the prototype look more finished.", dimension: "experienceDesign", reverse: false, weights: { product: -1, ux: 3, interaction: -3, research: 3, systems: 0, technology: -2, humanFactors: 1, content: 1 } },
    { id: "q07", prompt: "If a flow mostly works, I would rather improve the final-screen presentation than reopen the messy middle steps.", dimension: "experienceDesign", reverse: false, weights: { product: 0, ux: -3, interaction: 3, research: -2, systems: 0, technology: 1, humanFactors: -1, content: -1 } },
    { id: "q08", prompt: "I get more energy from specifying states, timing, feedback, and transitions than from explaining the product strategy.", dimension: "experienceDesign", reverse: false, weights: { product: -2, ux: 1, interaction: 3, research: -1, systems: 1, technology: 2, humanFactors: 0, content: 0 } },
    { id: "q09", prompt: "I would rather lock the information architecture and content hierarchy before making the prototype feel real.", dimension: "experienceDesign", reverse: false, weights: { product: 1, ux: 3, interaction: -2, research: 1, systems: 2, technology: -2, humanFactors: 1, content: 3 } },
    { id: "q10", prompt: "I would choose a distinctive custom interaction over a familiar pattern if it makes the experience feel more memorable.", dimension: "experienceDesign", reverse: false, weights: { product: 0, ux: -1, interaction: 3, research: -1, systems: -3, technology: 1, humanFactors: -2, content: 0 } },
    { id: "q11", prompt: "If stakeholders are aligned and the risk seems low, I am comfortable moving forward with limited user research.", dimension: "research", reverse: false, weights: { product: 1, ux: -2, interaction: 0, research: -3, systems: 0, technology: 2, humanFactors: -2, content: 0 } },
    { id: "q12", prompt: "I would rather make stakeholders sit with uncertain research findings than give them a clean recommendation too early.", dimension: "research", reverse: false, weights: { product: -2, ux: 1, interaction: -1, research: 3, systems: 0, technology: -2, humanFactors: 2, content: 1 } },
    { id: "q13", prompt: "In a portfolio project, a working coded demo usually signals more value than a detailed research appendix.", dimension: "research", reverse: false, weights: { product: 0, ux: -1, interaction: 2, research: -3, systems: 0, technology: 3, humanFactors: -1, content: -2 } },
    { id: "q14", prompt: "In a portfolio project, the decision story and evidence matter more than whether the prototype is coded.", dimension: "research", reverse: false, weights: { product: 1, ux: 2, interaction: -1, research: 3, systems: 0, technology: -3, humanFactors: 1, content: 2 } },
    { id: "q15", prompt: "I would rather use product metrics and behavioral data than rely mainly on interview quotes when deciding what to build next.", dimension: "research", reverse: false, weights: { product: 2, ux: -1, interaction: 0, research: -1, systems: 0, technology: 2, humanFactors: -1, content: -1 } },
    { id: "q16", prompt: "If the design system component is a poor fit for the user task, I would customize the experience instead of forcing consistency.", dimension: "systems", reverse: false, weights: { product: 0, ux: 2, interaction: 2, research: 0, systems: -3, technology: -1, humanFactors: 1, content: 0 } },
    { id: "q17", prompt: "I would rather reuse a slightly imperfect pattern than create a custom interaction that only works for one screen.", dimension: "systems", reverse: false, weights: { product: -1, ux: -1, interaction: -3, research: 0, systems: 3, technology: 2, humanFactors: 1, content: 0 } },
    { id: "q18", prompt: "I get more satisfaction from fixing a shared component everyone uses than from designing a new feature screen.", dimension: "systems", reverse: false, weights: { product: -2, ux: 0, interaction: -2, research: 0, systems: 3, technology: 2, humanFactors: 1, content: 1 } },
    { id: "q19", prompt: "For a first client demo, I can tolerate inconsistent components if the product story lands clearly.", dimension: "systems", reverse: false, weights: { product: 2, ux: 0, interaction: 1, research: -1, systems: -3, technology: 1, humanFactors: -1, content: 1 } },
    { id: "q20", prompt: "Before others reuse a pattern, I want usage rules, accessibility notes, and edge cases documented.", dimension: "systems", reverse: false, weights: { product: -2, ux: 1, interaction: 0, research: 1, systems: 3, technology: 1, humanFactors: 2, content: 2 } },
    { id: "q21", prompt: "If a coded prototype exposes feasibility faster, I am willing to let the first UX flow be rougher.", dimension: "build", reverse: false, weights: { product: 1, ux: -3, interaction: 1, research: -2, systems: 0, technology: 3, humanFactors: -1, content: -1 } },
    { id: "q22", prompt: "For an executive or client review, I would rather bring a high-fidelity prototype than a low-fidelity artifact designed for discussion.", dimension: "build", reverse: false, weights: { product: 1, ux: -2, interaction: 3, research: -3, systems: 0, technology: 3, humanFactors: -1, content: -1 } },
    { id: "q23", prompt: "When engineering constraints appear, I want to understand the code-level issue and adapt the design around it.", dimension: "build", reverse: false, weights: { product: 1, ux: 0, interaction: -1, research: 0, systems: 2, technology: 3, humanFactors: 0, content: 0 } },
    { id: "q24", prompt: "If engineering constraints weaken the user experience, I would rather push back and explore alternatives than adapt too quickly.", dimension: "build", reverse: false, weights: { product: 0, ux: 3, interaction: 2, research: 1, systems: 0, technology: -2, humanFactors: 1, content: 0 } },
    { id: "q25", prompt: "I prefer working close to launch details, responsive behavior, implementation bugs, and QA, over early discovery work.", dimension: "build", reverse: false, weights: { product: -1, ux: -1, interaction: 1, research: -3, systems: 2, technology: 3, humanFactors: 0, content: -1 } },
    { id: "q26", prompt: "I would sacrifice some accessibility or edge-case coverage if that is what lets the team hit a critical demo date.", dimension: "humanFactors", reverse: false, weights: { product: 2, ux: -2, interaction: 1, research: -1, systems: -2, technology: 2, humanFactors: -3, content: -1 } },
    { id: "q27", prompt: "I would rather reduce scope than ship something that creates avoidable user mistakes or unsafe behavior.", dimension: "humanFactors", reverse: false, weights: { product: 1, ux: 1, interaction: -1, research: 2, systems: 1, technology: -2, humanFactors: 3, content: 1 } },
    { id: "q28", prompt: "For a safety-critical or medical context, I would slow down a flashy demo to document risks, training, and recovery paths.", dimension: "humanFactors", reverse: false, weights: { product: -1, ux: 1, interaction: -2, research: 2, systems: 2, technology: -2, humanFactors: 3, content: 2 } },
    { id: "q29", prompt: "For a consumer app or class project, I am more willing to move fast and test live than fully analyze rare error paths.", dimension: "humanFactors", reverse: false, weights: { product: 1, ux: -1, interaction: 1, research: -2, systems: -2, technology: 2, humanFactors: -3, content: 0 } },
    { id: "q30", prompt: "I am comfortable relying on onboarding or training if it lets the product support a more powerful workflow.", dimension: "humanFactors", reverse: false, weights: { product: 1, ux: -2, interaction: 0, research: -1, systems: 0, technology: 2, humanFactors: -2, content: 1 } },
    { id: "q31", prompt: "The words in empty states, errors, and helper text can wait until the flow and visuals are mostly locked.", dimension: "content", reverse: false, weights: { product: -1, ux: -2, interaction: 2, research: -1, systems: 0, technology: 2, humanFactors: -2, content: -3 } },
    { id: "q32", prompt: "I would cut visual polish before cutting clear labels, instructions, and recovery messages.", dimension: "content", reverse: false, weights: { product: -1, ux: 2, interaction: -3, research: 1, systems: 1, technology: -1, humanFactors: 2, content: 3 } },
    { id: "q33", prompt: "I enjoy changing the layout if that is what makes the navigation, labels, or call-to-action copy clearer.", dimension: "content", reverse: false, weights: { product: 0, ux: 2, interaction: -1, research: 1, systems: 1, technology: -1, humanFactors: 1, content: 3 } },
    { id: "q34", prompt: "I would preserve a strong layout and interaction pattern even if the copy is only technically understandable.", dimension: "content", reverse: false, weights: { product: 0, ux: -2, interaction: 2, research: -1, systems: 1, technology: 1, humanFactors: -1, content: -3 } },
    { id: "q35", prompt: "For a career fair or stakeholder demo, I would bring a live demo over a slide case study explaining the reasoning.", dimension: "content", reverse: false, weights: { product: 0, ux: -1, interaction: 2, research: -3, systems: 0, technology: 3, humanFactors: -1, content: -2 } },
  ],
  tieBreakerLogic: {
    showSecondaryIfWithin: 5,
    showBlendedIfWithin: 3,
    blendPairs: [
      ["ux", "interaction"],
      ["product", "research"],
      ["systems", "technology"],
      ["research", "humanFactors"],
      ["ux", "content"],
    ],
  },
  biasAndValidityNotes: [
    "This is a directional self-reflection tool, not a validated career diagnosis.",
    "Role titles overlap across companies, so adjacent roles should be shown as nearby paths rather than wrong answers.",
    "Use preference-based wording more than achievement-based wording so students with limited internships are not penalized.",
    "Keep reverse-scored items simple and few; avoid dense negations or trick wording.",
  ],
};
