window.DESIGNER_TYPE_TEST = {
  scale: [
    { value: 1, label: "Strongly disagree" },
    { value: 2, label: "Disagree" },
    { value: 3, label: "Neutral" },
    { value: 4, label: "Agree" },
    { value: 5, label: "Strongly agree" },
  ],
  dimensions: [
    { id: "strategy", name: "Strategic product framing", summary: "Connecting user needs, constraints, scope, and outcomes." },
    { id: "experienceDesign", name: "Experience design and interaction craft", summary: "Structuring flows, information, states, feedback, and behavior." },
    { id: "research", name: "Research and evidence orientation", summary: "Learning from users, reducing bias, and synthesizing evidence." },
    { id: "systems", name: "Systems and consistency thinking", summary: "Reusable patterns, standards, tokens, documentation, and accessibility." },
    { id: "build", name: "Technical implementation and prototyping", summary: "Working in code, feasibility, and design-to-build quality." },
    { id: "humanFactors", name: "Human factors and risk sensitivity", summary: "Understanding users, environments, safety, ergonomics, and error prevention." },
    { id: "content", name: "Content clarity and narrative design", summary: "Designing with words, naming, microcopy, and content standards." },
  ],
  types: [
    {
      id: "product",
      name: "Product Designer",
      color: "#d29b2f",
      summary: "You like connecting user needs, product direction, constraints, and interface quality into one coherent decision path.",
      strengths: ["Problem framing", "Scoping and tradeoffs", "Cross-functional decision making", "End-to-end product thinking"],
      projectIdeas: [
        "Redesign a campus workflow and justify what changed and why",
        "Create an MVP feature concept with user problem, scope, flows, and success signals",
        "Compare two product directions and defend a recommendation",
      ],
      skillsToBuild: ["Product thinking and prioritization", "Journey mapping", "Usability testing basics", "Clear design rationale and presentation"],
      rolesToExplore: ["Product Designer", "Associate Product Designer", "Growth Designer", "Product-minded UX Designer"],
      priorityDimensions: ["strategy", "research", "experienceDesign"],
      recruitingCompanies: [
        { name: "Meta", url: "https://www.metacareers.com/", logo: "assets/company-logos/META.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Abbott", url: "https://www.jobs.abbott/", logo: "assets/company-logos/ABT.png" },
      ],
      additionalCompanies: ["Airbnb", "Intuit", "Art of Problem Solving"],
    },
    {
      id: "ux",
      name: "UX Designer",
      color: "#2f9c95",
      summary: "You are most energized by making tasks understandable, flows usable, and navigation clearer for real people.",
      strengths: ["Flow design", "Information architecture", "Usability improvement", "Wireframing and iteration"],
      projectIdeas: [
        "Untangle a confusing multi-step student flow",
        "Redesign a dense dashboard for clarity and task completion",
        "Run a lightweight usability test on a campus or club tool",
      ],
      skillsToBuild: ["Information architecture", "Wireframing and prototyping", "Usability heuristics", "Accessibility basics"],
      rolesToExplore: ["UX Designer", "Experience Designer", "Product Designer with UX emphasis", "Service Designer intern"],
      priorityDimensions: ["experienceDesign", "research", "content"],
      recruitingCompanies: [
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
      ],
      additionalCompanies: ["Intuit", "ServiceNow", "Salesforce"],
    },
    {
      id: "interaction",
      name: "Interaction Designer",
      color: "#1f7ae0",
      summary: "You care about what the interface does moment to moment: states, feedback, timing, transitions, and behavioral clarity.",
      strengths: ["Interaction detail", "State modeling", "Microinteractions", "High-fidelity prototyping"],
      projectIdeas: [
        "Prototype a small but polished interaction with loading, hover, focus, error, and success states",
        "Design a set of onboarding interactions and explain the behavior rules",
        "Create a motion or transition spec for a mobile flow",
      ],
      skillsToBuild: ["State diagrams and interaction specs", "Advanced prototyping", "Motion and feedback principles", "Front-end fundamentals for implementation-aware design"],
      rolesToExplore: ["Interaction Designer", "Product Designer with interaction focus", "Prototype Designer", "Motion or interaction-focused UX role"],
      priorityDimensions: ["experienceDesign", "build", "systems"],
      recruitingCompanies: [
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Figma", url: "https://www.figma.com/careers/", logo: "assets/company-logos/FIG.png" },
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
      ],
      additionalCompanies: ["Apple", "Airbnb", "Duolingo"],
    },
    {
      id: "research",
      name: "UX Researcher",
      color: "#3b79b7",
      summary: "You are motivated by evidence, interviews, synthesis, and helping teams make better decisions under uncertainty.",
      strengths: ["Study planning", "Interviewing and observation", "Insight synthesis", "Evidence-based communication"],
      projectIdeas: [
        "Run a usability study on a student app and synthesize findings",
        "Conduct interviews about how students plan coursework or internships",
        "Compare survey and interview results on a design question",
      ],
      skillsToBuild: ["Moderated interviewing", "Study design and bias reduction", "Affinity mapping and synthesis", "Basic quantitative reasoning"],
      rolesToExplore: ["UX Researcher", "Research Assistant in HCI or CogSci", "Product Research Intern", "Design Researcher"],
      priorityDimensions: ["research", "humanFactors", "strategy"],
      recruitingCompanies: [
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
      ],
      additionalCompanies: ["Meta", "Spotify", "Intuit"],
    },
    {
      id: "systems",
      name: "Design Systems Designer",
      color: "#7c5cbf",
      summary: "You like creating reusable patterns, shared standards, and accessible consistency that scale across many screens and teams.",
      strengths: ["Pattern recognition", "Reusable component thinking", "Documentation and governance", "Accessibility-minded consistency"],
      projectIdeas: [
        "Create a mini design system for a club or campus app",
        "Audit an interface for inconsistency and propose reusable fixes",
        "Document a component library with usage rules and accessibility notes",
      ],
      skillsToBuild: ["Component anatomy and tokens", "Figma libraries and variants", "Documentation and adoption strategy", "Accessibility and standards"],
      rolesToExplore: ["Design Systems Designer", "Systems-focused Product Designer", "UI Systems Designer", "DesignOps-adjacent systems role"],
      priorityDimensions: ["systems", "build", "content"],
      recruitingCompanies: [
        { name: "Figma", url: "https://www.figma.com/careers/", logo: "assets/company-logos/FIG.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
      ],
      additionalCompanies: ["Salesforce", "Atlassian", "Shopify", "IBM"],
    },
    {
      id: "technology",
      name: "Design Technologist / UI Engineer",
      color: "#55a66f",
      summary: "You want to turn ideas into working interfaces, prove feasibility in code, and keep design quality intact during implementation.",
      strengths: ["Code-based prototyping", "Engineering collaboration", "Technical feasibility judgment", "Implementation quality"],
      projectIdeas: [
        "Build a coded prototype with real states and data",
        "Create an accessible reusable component in HTML/CSS/JS or React",
        "Turn a Figma concept into a responsive front-end demo",
      ],
      skillsToBuild: ["HTML, CSS, and JavaScript", "Component-based front-end development", "Accessibility in code", "Browser devtools and implementation debugging"],
      rolesToExplore: ["Design Technologist", "UX Engineer", "UI Engineer", "Design Engineer", "Front-end prototyper"],
      priorityDimensions: ["build", "experienceDesign", "systems"],
      recruitingCompanies: [
        { name: "Amazon", url: "https://www.amazon.jobs/", logo: "assets/company-logos/AMZN.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
        { name: "Booz Allen", url: "https://careers.boozallen.com/", logo: "assets/company-logos/BAH.png" },
      ],
      additionalCompanies: ["IMDb", "Airbnb", "Vercel"],
    },
    {
      id: "humanFactors",
      name: "Human Factors Engineer",
      color: "#c85d3a",
      summary: "You are drawn to systems where safety, error prevention, ergonomics, and real-world context matter as much as visual polish.",
      strengths: ["Task and context analysis", "Risk and error prevention", "Evaluation in realistic conditions", "Human performance thinking"],
      projectIdeas: [
        "Analyze a high-stakes check-in or scheduling flow for error risks and recovery",
        "Redesign a kiosk, device workflow, or public-service experience for safer use",
        "Create a usability validation plan for a complex tool or device companion app",
      ],
      skillsToBuild: ["Task analysis and use scenarios", "Risk analysis and error taxonomy", "Usability validation methods", "Accessibility and ergonomics literacy"],
      rolesToExplore: ["Human Factors Engineer", "Usability Engineer", "Ergonomist", "Human-Systems Integration role", "Safety-critical UX role"],
      priorityDimensions: ["humanFactors", "research", "systems"],
      recruitingCompanies: [
        { name: "Illumina", url: "https://www.illumina.com/company/careers.html", logo: "assets/company-logos/ILMN.png" },
        { name: "Sony", url: "https://www.sony.com/en/SonyInfo/Careers/", logo: "assets/company-logos/SONY.png" },
        { name: "Becton Dickinson", url: "https://jobs.bd.com/", logo: "assets/company-logos/BDX.png" },
      ],
      additionalCompanies: ["Dexcom", "Medtronic", "Abbott"],
    },
    {
      id: "content",
      name: "UX Writer / Content Designer",
      color: "#cc4f8b",
      summary: "You think design quality depends on the words as much as the screens, and you care about clarity, naming, tone, and content systems.",
      strengths: ["Microcopy and naming", "Clarity and tone", "Content patterns and standards", "Cross-team language consistency"],
      projectIdeas: [
        "Rewrite onboarding and error copy for a real app concept",
        "Create naming and microcopy rules for a component set",
        "Run a content-focused usability test on instructions or form errors",
      ],
      skillsToBuild: ["UX writing and microcopy", "Voice and tone systems", "Content testing", "Structured content and design collaboration"],
      rolesToExplore: ["UX Writer", "Content Designer", "Product Content Strategist", "Conversation-design adjacent role"],
      priorityDimensions: ["content", "experienceDesign", "research"],
      recruitingCompanies: [
        { name: "Figma", url: "https://www.figma.com/careers/", logo: "assets/company-logos/FIG.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Meta", url: "https://www.metacareers.com/", logo: "assets/company-logos/META.png" },
      ],
      additionalCompanies: ["Airbnb", "Intuit", "Notion"],
    },
  ],
  questions: [
    { id: "q01", prompt: "I enjoy turning an ambiguous product problem into a clear plan a team could actually act on.", dimension: "strategy", reverse: false, weights: { product: 3, ux: 1, interaction: 0, research: 1, systems: 0, technology: 0, humanFactors: 1, content: 0 } },
    { id: "q02", prompt: "I care whether a feature will change user behavior or product outcomes, not just whether the screen looks good.", dimension: "strategy", reverse: false, weights: { product: 3, ux: 1, interaction: 0, research: 1, systems: 0, technology: 0, humanFactors: 0, content: 1 } },
    { id: "q03", prompt: "When there are several ways to solve a problem, I like comparing tradeoffs before choosing a direction.", dimension: "strategy", reverse: false, weights: { product: 2, ux: 1, interaction: 1, research: 1, systems: 1, technology: 0, humanFactors: 0, content: 0 } },
    { id: "q04", prompt: "If a concept is exciting but unrealistic this semester, I would rather scope it down than defend the original idea.", dimension: "strategy", reverse: false, weights: { product: 3, ux: 0, interaction: 0, research: 0, systems: 1, technology: 1, humanFactors: 0, content: 0 } },
    { id: "q05", prompt: "I would rather focus on one screen than think about how a choice affects the rest of the product.", dimension: "strategy", reverse: true, weights: { product: 3, ux: 2, interaction: 1, research: 0, systems: 1, technology: 0, humanFactors: 0, content: 0 } },
    { id: "q06", prompt: "I would rather untangle a confusing multi-step flow than make a single screen look more polished.", dimension: "experienceDesign", reverse: false, weights: { product: 1, ux: 3, interaction: 1, research: 1, systems: 0, technology: 0, humanFactors: 1, content: 0 } },
    { id: "q07", prompt: "I notice weak labels, confusing navigation, or category structures quickly.", dimension: "experienceDesign", reverse: false, weights: { product: 1, ux: 3, interaction: 1, research: 1, systems: 0, technology: 0, humanFactors: 0, content: 1 } },
    { id: "q08", prompt: "I enjoy specifying hover, focus, loading, success, empty, and error states.", dimension: "experienceDesign", reverse: false, weights: { product: 0, ux: 1, interaction: 3, research: 0, systems: 1, technology: 1, humanFactors: 1, content: 0 } },
    { id: "q09", prompt: "I care a lot about feedback timing, motion, and what the interface does immediately after each user action.", dimension: "experienceDesign", reverse: false, weights: { product: 0, ux: 1, interaction: 3, research: 0, systems: 1, technology: 1, humanFactors: 1, content: 0 } },
    { id: "q10", prompt: "Once the main screens exist, details like transitions, states, and edge-case behaviors are usually not worth much extra time.", dimension: "experienceDesign", reverse: true, weights: { product: 0, ux: 1, interaction: 3, research: 0, systems: 0, technology: 1, humanFactors: 1, content: 0 } },
    { id: "q11", prompt: "I would rather talk to a handful of real users than keep debating assumptions in a critique.", dimension: "research", reverse: false, weights: { product: 1, ux: 1, interaction: 0, research: 3, systems: 0, technology: 0, humanFactors: 1, content: 1 } },
    { id: "q12", prompt: "I like turning messy notes, recordings, or observations into patterns that change design decisions.", dimension: "research", reverse: false, weights: { product: 1, ux: 0, interaction: 0, research: 3, systems: 0, technology: 0, humanFactors: 1, content: 1 } },
    { id: "q13", prompt: "Before choosing a direction, I naturally ask what evidence would actually change our minds.", dimension: "research", reverse: false, weights: { product: 1, ux: 0, interaction: 0, research: 3, systems: 1, technology: 0, humanFactors: 1, content: 0 } },
    { id: "q14", prompt: "Writing a study plan, interview guide, or test task sounds more energizing than intimidating.", dimension: "research", reverse: false, weights: { product: 0, ux: 1, interaction: 0, research: 3, systems: 0, technology: 0, humanFactors: 1, content: 1 } },
    { id: "q15", prompt: "If a design seems intuitive to the team, formal testing usually feels unnecessary.", dimension: "research", reverse: true, weights: { product: 1, ux: 2, interaction: 0, research: 3, systems: 0, technology: 0, humanFactors: 2, content: 0 } },
    { id: "q16", prompt: "I notice inconsistent components, spacing, interaction patterns, or accessibility behavior almost immediately.", dimension: "systems", reverse: false, weights: { product: 0, ux: 1, interaction: 1, research: 0, systems: 3, technology: 0, humanFactors: 1, content: 0 } },
    { id: "q17", prompt: "I like creating reusable rules, components, or templates that other people can follow.", dimension: "systems", reverse: false, weights: { product: 0, ux: 1, interaction: 0, research: 0, systems: 3, technology: 1, humanFactors: 0, content: 1 } },
    { id: "q18", prompt: "Documenting patterns so multiple teams can move faster sounds meaningful to me.", dimension: "systems", reverse: false, weights: { product: 1, ux: 0, interaction: 0, research: 0, systems: 3, technology: 1, humanFactors: 0, content: 1 } },
    { id: "q19", prompt: "I would rather improve one core component used everywhere than redesign one flashy screen.", dimension: "systems", reverse: false, weights: { product: 1, ux: 1, interaction: 0, research: 0, systems: 3, technology: 1, humanFactors: 0, content: 0 } },
    { id: "q20", prompt: "I am comfortable trading a little novelty for a lot more consistency when an existing pattern already works well.", dimension: "systems", reverse: false, weights: { product: 1, ux: 1, interaction: 0, research: 0, systems: 3, technology: 1, humanFactors: 1, content: 0 } },
    { id: "q21", prompt: "I am willing to write code if it helps test whether an idea is feasible or high quality.", dimension: "build", reverse: false, weights: { product: 1, ux: 0, interaction: 1, research: 0, systems: 1, technology: 3, humanFactors: 0, content: 0 } },
    { id: "q22", prompt: "I want design files and production UI to stay closely aligned instead of drifting apart during implementation.", dimension: "build", reverse: false, weights: { product: 0, ux: 0, interaction: 1, research: 0, systems: 2, technology: 3, humanFactors: 0, content: 0 } },
    { id: "q23", prompt: "I enjoy building prototypes with real data, real states, or real front-end constraints.", dimension: "build", reverse: false, weights: { product: 1, ux: 0, interaction: 2, research: 0, systems: 1, technology: 3, humanFactors: 1, content: 0 } },
    { id: "q24", prompt: "I like inspecting components in the browser and understanding how the interface is actually implemented.", dimension: "build", reverse: false, weights: { product: 0, ux: 1, interaction: 1, research: 0, systems: 1, technology: 3, humanFactors: 0, content: 0 } },
    { id: "q25", prompt: "Handing designs off is more appealing to me than staying involved while the interface gets built.", dimension: "build", reverse: true, weights: { product: 1, ux: 0, interaction: 1, research: 0, systems: 1, technology: 3, humanFactors: 0, content: 0 } },
    { id: "q26", prompt: "I think a lot about where people could make mistakes, especially when they are rushed, distracted, or under pressure.", dimension: "humanFactors", reverse: false, weights: { product: 0, ux: 0, interaction: 1, research: 1, systems: 1, technology: 0, humanFactors: 3, content: 0 } },
    { id: "q27", prompt: "I am drawn to designing safer, clearer systems for complex or high-stakes contexts.", dimension: "humanFactors", reverse: false, weights: { product: 1, ux: 0, interaction: 0, research: 1, systems: 1, technology: 0, humanFactors: 3, content: 0 } },
    { id: "q28", prompt: "I like analyzing users, environments, and constraints together rather than looking only at the interface itself.", dimension: "humanFactors", reverse: false, weights: { product: 1, ux: 1, interaction: 0, research: 1, systems: 0, technology: 0, humanFactors: 3, content: 0 } },
    { id: "q29", prompt: "For me, ergonomics, accessibility, instructions, error prevention, and recovery are part of design quality, not extra polish.", dimension: "humanFactors", reverse: false, weights: { product: 0, ux: 1, interaction: 0, research: 0, systems: 1, technology: 0, humanFactors: 3, content: 1 } },
    { id: "q30", prompt: "I prefer products that are easy to use safely without extra training whenever possible.", dimension: "humanFactors", reverse: false, weights: { product: 0, ux: 1, interaction: 0, research: 1, systems: 1, technology: 0, humanFactors: 3, content: 1 } },
    { id: "q31", prompt: "I enjoy rewriting interface text until instructions feel clear, concise, and human.", dimension: "content", reverse: false, weights: { product: 0, ux: 1, interaction: 1, research: 1, systems: 0, technology: 0, humanFactors: 0, content: 3 } },
    { id: "q32", prompt: "I notice when a product's words and interaction choices send mixed signals.", dimension: "content", reverse: false, weights: { product: 0, ux: 1, interaction: 1, research: 0, systems: 1, technology: 0, humanFactors: 0, content: 3 } },
    { id: "q33", prompt: "Naming, tone, and microcopy matter to me because they change whether people can complete tasks.", dimension: "content", reverse: false, weights: { product: 1, ux: 1, interaction: 0, research: 1, systems: 0, technology: 0, humanFactors: 0, content: 3 } },
    { id: "q34", prompt: "I would rather create a content pattern or writing guideline than invent one-off copy each time.", dimension: "content", reverse: false, weights: { product: 0, ux: 1, interaction: 0, research: 0, systems: 1, technology: 0, humanFactors: 0, content: 3 } },
    { id: "q35", prompt: "Copy can be fixed late; the real design work happens before the words.", dimension: "content", reverse: true, weights: { product: 1, ux: 2, interaction: 0, research: 0, systems: 1, technology: 0, humanFactors: 0, content: 3 } },
  ],
  tieBreakerLogic: {
    showSecondaryIfWithin: 5,
    showBlendedIfWithin: 3,
    blendPairs: [
      ["ux", "interaction"],
      ["product", "research"],
      ["systems", "technology"],
      ["research", "humanFactors"],
      ["ux", "content"],
    ],
  },
  biasAndValidityNotes: [
    "This is a directional self-reflection tool, not a validated career diagnosis.",
    "Role titles overlap across companies, so adjacent roles should be shown as nearby paths rather than wrong answers.",
    "Use preference-based wording more than achievement-based wording so students with limited internships are not penalized.",
    "Keep reverse-scored items simple and few; avoid dense negations or trick wording.",
  ],
};
