window.DESIGNER_TYPE_TEST = {
  scale: [
    { value: 1, label: "Strongly disagree" },
    { value: 2, label: "Disagree" },
    { value: 3, label: "Neutral" },
    { value: 4, label: "Agree" },
    { value: 5, label: "Strongly agree" },
  ],
  dimensions: [
    { id: "strategy", name: "Strategic product framing", summary: "Connecting user needs, constraints, scope, and outcomes." },
    { id: "experienceDesign", name: "Experience design and interaction craft", summary: "Structuring flows, information, states, feedback, and behavior." },
    { id: "research", name: "Research and evidence orientation", summary: "Learning from users, reducing bias, and synthesizing evidence." },
    { id: "systems", name: "Systems and consistency thinking", summary: "Reusable patterns, standards, tokens, documentation, and accessibility." },
    { id: "build", name: "Technical implementation and prototyping", summary: "Working in code, feasibility, and design-to-build quality." },
    { id: "humanFactors", name: "Human factors and risk sensitivity", summary: "Understanding users, environments, safety, ergonomics, and error prevention." },
    { id: "content", name: "Content clarity and narrative design", summary: "Designing with words, naming, microcopy, and content standards." },
  ],
  types: [
    {
      id: "product",
      name: "Product Designer",
      color: "#d29b2f",
      summary: "You like connecting user needs, product direction, constraints, and interface quality into one coherent decision path.",
      strengths: ["Problem framing", "Scoping and tradeoffs", "Cross-functional decision making", "End-to-end product thinking", "Cross-product consistency judgment", "Pattern adoption tradeoffs"],
      projectIdeas: [
        "Redesign a campus workflow and justify what changed and why",
        "Create an MVP feature concept with user problem, scope, flows, and success signals",
        "Compare two product directions and defend a recommendation",
        "Create a feature concept that balances product goals with reusable patterns",
      ],
      skillsToBuild: ["Product thinking and prioritization", "Journey mapping", "Usability testing basics", "Clear design rationale and presentation", "Design system governance basics"],
      rolesToExplore: ["Product Designer", "Associate Product Designer", "Growth Designer", "Product-minded UX Designer"],
      priorityDimensions: ["strategy", "research", "experienceDesign"],
      recruitingCompanies: [
        { name: "Meta", url: "https://www.metacareers.com/", logo: "assets/company-logos/META.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Abbott", url: "https://www.jobs.abbott/", logo: "assets/company-logos/ABT.png" },
      ],
      additionalCompanies: ["Airbnb", "Intuit", "Art of Problem Solving", "Salesforce", "Atlassian"],
    },
    {
      id: "ux",
      name: "UX Designer",
      color: "#2f9c95",
      summary: "You are most energized by making tasks understandable, flows usable, and navigation clearer for real people.",
      strengths: ["Flow design", "Information architecture", "Usability improvement", "Wireframing and iteration", "Reusable flow patterns", "Consistency across user journeys"],
      projectIdeas: [
        "Untangle a confusing multi-step student flow",
        "Redesign a dense dashboard for clarity and task completion",
        "Run a lightweight usability test on a campus or club tool",
        "Audit a campus workflow for inconsistent patterns and confusing hierarchy",
      ],
      skillsToBuild: ["Information architecture", "Wireframing and prototyping", "Usability heuristics", "Pattern libraries", "Accessibility heuristics"],
      rolesToExplore: ["UX Designer", "Experience Designer", "Product Designer with UX emphasis", "Service Designer intern"],
      priorityDimensions: ["experienceDesign", "research", "content"],
      recruitingCompanies: [
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
      ],
      additionalCompanies: ["Intuit", "ServiceNow", "Salesforce", "Shopify"],
    },
    {
      id: "interaction",
      name: "Interaction Designer",
      color: "#1f7ae0",
      summary: "You care about what the interface does moment to moment: states, feedback, timing, transitions, and behavioral clarity.",
      strengths: ["Interaction detail", "State modeling", "Microinteractions", "High-fidelity prototyping", "Reusable interaction behavior", "Component state logic"],
      projectIdeas: [
        "Prototype a small but polished interaction with loading, hover, focus, error, and success states",
        "Design a set of onboarding interactions and explain the behavior rules",
        "Create a motion or transition spec for a mobile flow",
        "Create a reusable interaction spec for loading, empty, error, and success states",
      ],
      skillsToBuild: ["State diagrams and interaction specs", "Advanced prototyping", "Motion and feedback principles", "Component behavior specs", "Interaction pattern documentation"],
      rolesToExplore: ["Interaction Designer", "Product Designer with interaction focus", "Prototype Designer", "Motion or interaction-focused UX role"],
      priorityDimensions: ["experienceDesign", "build", "systems"],
      recruitingCompanies: [
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Figma", url: "https://www.figma.com/careers/", logo: "assets/company-logos/FIG.png" },
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
      ],
      additionalCompanies: ["Apple", "Airbnb", "Duolingo", "Microsoft"],
    },
    {
      id: "research",
      name: "UX Researcher",
      color: "#3b79b7",
      summary: "You are motivated by evidence, interviews, synthesis, and helping teams make better decisions under uncertainty.",
      strengths: ["Study planning", "Interviewing and observation", "Insight synthesis", "Evidence-based communication", "Research documentation", "Evidence standards"],
      projectIdeas: [
        "Run a usability study on a student app and synthesize findings",
        "Conduct interviews about how students plan coursework or internships",
        "Compare survey and interview results on a design question",
        "Build a lightweight research repository for recurring product decisions",
      ],
      skillsToBuild: ["Moderated interviewing", "Study design and bias reduction", "Affinity mapping and synthesis", "Basic quantitative reasoning", "Research repository structure"],
      rolesToExplore: ["UX Researcher", "Research Assistant in HCI or CogSci", "Product Research Intern", "Design Researcher"],
      priorityDimensions: ["research", "humanFactors", "strategy"],
      recruitingCompanies: [
        { name: "Adobe", url: "https://careers.adobe.com/", logo: "assets/company-logos/ADBE.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
      ],
      additionalCompanies: ["Meta", "Spotify", "Intuit", "IBM"],
    },
    {
      id: "technology",
      name: "Design Technologist / UI Engineer",
      color: "#55a66f",
      summary: "You want to turn ideas into working interfaces, prove feasibility in code, and keep design quality intact during implementation.",
      strengths: ["Code-based prototyping", "Engineering collaboration", "Technical feasibility judgment", "Implementation quality", "Reusable component engineering", "Design-to-code system thinking", "Token and component implementation"],
      projectIdeas: [
        "Build a coded prototype with real states and data",
        "Create an accessible reusable component in HTML/CSS/JS or React",
        "Turn a Figma concept into a responsive front-end demo",
        "Build a small accessible component library in HTML/CSS/JS or React",
        "Convert design tokens into working UI variables",
      ],
      skillsToBuild: ["HTML, CSS, and JavaScript", "Component-based front-end development", "Accessibility in code", "Browser devtools and implementation debugging", "Design tokens", "Storybook or component documentation", "Accessible component APIs"],
      rolesToExplore: ["Design Technologist", "UX Engineer", "UI Engineer", "Design Engineer", "Front-end prototyper"],
      priorityDimensions: ["build", "experienceDesign", "systems"],
      recruitingCompanies: [
        { name: "Amazon", url: "https://www.amazon.jobs/", logo: "assets/company-logos/AMZN.png" },
        { name: "Microsoft", url: "https://careers.microsoft.com/", logo: "assets/company-logos/MSFT.png" },
        { name: "Booz Allen", url: "https://careers.boozallen.com/", logo: "assets/company-logos/BAH.png" },
      ],
      additionalCompanies: ["IMDb", "Airbnb", "Vercel", "Figma", "Atlassian", "Shopify", "IBM"],
    },
    {
      id: "humanFactors",
      name: "Human Factors Engineer",
      color: "#c85d3a",
      summary: "You are drawn to systems where safety, error prevention, ergonomics, and real-world context matter as much as visual polish.",
      strengths: ["Task and context analysis", "Risk and error prevention", "Evaluation in realistic conditions", "Human performance thinking", "Safe default patterns", "Accessibility standards"],
      projectIdeas: [
        "Analyze a high-stakes check-in or scheduling flow for error risks and recovery",
        "Redesign a kiosk, device workflow, or public-service experience for safer use",
        "Create a usability validation plan for a complex tool or device companion app",
        "Create a reusable error-prevention checklist for a high-stakes workflow",
      ],
      skillsToBuild: ["Task analysis and use scenarios", "Risk analysis and error taxonomy", "Usability validation methods", "Accessibility and ergonomics literacy", "Accessibility standards", "Risk-informed pattern design"],
      rolesToExplore: ["Human Factors Engineer", "Usability Engineer", "Ergonomist", "Human-Systems Integration role", "Safety-critical UX role"],
      priorityDimensions: ["humanFactors", "research", "systems"],
      recruitingCompanies: [
        { name: "Illumina", url: "https://www.illumina.com/company/careers.html", logo: "assets/company-logos/ILMN.png" },
        { name: "Sony", url: "https://www.sony.com/en/SonyInfo/Careers/", logo: "assets/company-logos/SONY.png" },
        { name: "Becton Dickinson", url: "https://jobs.bd.com/", logo: "assets/company-logos/BDX.png" },
      ],
      additionalCompanies: ["Dexcom", "Medtronic", "Abbott"],
    },
    {
      id: "content",
      name: "UX Writer / Content Designer",
      color: "#cc4f8b",
      summary: "You think design quality depends on the words as much as the screens, and you care about clarity, naming, tone, and content systems.",
      strengths: ["Microcopy and naming", "Clarity and tone", "Content patterns and standards", "Cross-team language consistency", "Content systems", "Reusable language patterns"],
      projectIdeas: [
        "Rewrite onboarding and error copy for a real app concept",
        "Create naming and microcopy rules for a component set",
        "Run a content-focused usability test on instructions or form errors",
        "Create writing guidelines for errors, empty states, and onboarding",
      ],
      skillsToBuild: ["UX writing and microcopy", "Voice and tone systems", "Content testing", "Structured content and design collaboration", "Content design systems", "Terminology governance"],
      rolesToExplore: ["UX Writer", "Content Designer", "Product Content Strategist", "Conversation-design adjacent role"],
      priorityDimensions: ["content", "experienceDesign", "research"],
      recruitingCompanies: [
        { name: "Figma", url: "https://www.figma.com/careers/", logo: "assets/company-logos/FIG.png" },
        { name: "Google", url: "https://careers.google.com/", logo: "assets/company-logos/google.png" },
        { name: "Meta", url: "https://www.metacareers.com/", logo: "assets/company-logos/META.png" },
      ],
      additionalCompanies: ["Airbnb", "Intuit", "Notion"],
    },
  ],
  questions: [
    { id: "q01", prompt: "Before choosing a direction, I want to understand user value, product outcome, constraints, implementation effort, and communication needs together.", dimension: "strategy", kind: "anchor", reverse: false, weights: { product: 3, ux: 2, interaction: 1, research: 2, technology: 1, humanFactors: 1, content: 1 } },
    { id: "q02", prompt: "For a client checkpoint, I would rather show a polished clickable prototype than a rough artifact with richer stakeholder notes and open questions.", dimension: "strategy", kind: "tradeoff", reverse: false, weights: { product: 1, ux: -2, interaction: 3, research: -2, technology: 2, humanFactors: -1, content: -1 } },
    { id: "q03", prompt: "I would rather stay focused on screen-level execution than be responsible for product scope, tradeoffs, and success criteria.", dimension: "strategy", kind: "tradeoff", reverse: false, weights: { product: -3, ux: 1, interaction: 2, research: 0, technology: 1, humanFactors: 0, content: 0 } },
    { id: "q04", prompt: "I am comfortable cutting an impressive feature if it does not support the outcome the product actually needs to achieve.", dimension: "strategy", kind: "tradeoff", reverse: false, weights: { product: 3, ux: 1, interaction: -2, research: 1, technology: 0, humanFactors: 1, content: 0 } },
    { id: "q05", prompt: "A strong designer should know when to stay low fidelity for alignment and when to raise fidelity or code a prototype for confidence.", dimension: "strategy", kind: "anchor", reverse: false, weights: { product: 2, ux: 2, interaction: 2, research: 2, technology: 2, humanFactors: 1, content: 1 } },
    { id: "q06", prompt: "Before polishing visuals, I want the task flow, navigation, and content hierarchy to be clear enough that a new user knows what to do.", dimension: "experienceDesign", kind: "anchor", reverse: false, weights: { product: 1, ux: 3, interaction: 0, research: 1, technology: 0, humanFactors: 1, content: 2 } },
    { id: "q07", prompt: "I would choose a distinctive custom interaction over a familiar pattern if it makes the experience feel more memorable.", dimension: "experienceDesign", kind: "tradeoff", reverse: false, weights: { product: 0, ux: -2, interaction: 3, research: -1, technology: 0, humanFactors: -2, content: 0 } },
    { id: "q08", prompt: "I enjoy specifying states, timing, feedback, loading, empty, error, and success behavior until the interaction feels precise.", dimension: "experienceDesign", kind: "anchor", reverse: false, weights: { product: 0, ux: 1, interaction: 3, research: 0, technology: 2, humanFactors: 1, content: 1 } },
    { id: "q09", prompt: "If the demo looks polished, I am less concerned when the middle steps of the experience are still awkward or underexplained.", dimension: "experienceDesign", kind: "tradeoff", reverse: false, weights: { product: 1, ux: -3, interaction: 2, research: -1, technology: 1, humanFactors: -2, content: -1 } },
    { id: "q10", prompt: "I want to observe or talk to users before the team commits significant time to a design direction.", dimension: "research", kind: "tradeoff", reverse: false, weights: { product: 1, ux: 2, interaction: -1, research: 3, technology: -1, humanFactors: 2, content: 1 } },
    { id: "q11", prompt: "In a portfolio or client review, a working coded demo usually signals more value than a detailed research appendix.", dimension: "research", kind: "tradeoff", reverse: false, weights: { product: 0, ux: -1, interaction: 2, research: -3, technology: 3, humanFactors: -1, content: -2 } },
    { id: "q12", prompt: "I get energy from turning messy notes, conflicting evidence, and uncertain observations into a clearer decision story.", dimension: "research", kind: "anchor", reverse: false, weights: { product: 1, ux: 1, interaction: 0, research: 3, technology: 0, humanFactors: 1, content: 1 } },
    { id: "q13", prompt: "If stakeholders agree and the timeline is tight, I am comfortable moving forward without validating the riskiest assumption.", dimension: "research", kind: "tradeoff", reverse: false, weights: { product: 1, ux: -2, interaction: 1, research: -3, technology: 2, humanFactors: -2, content: -1 } },
    { id: "q14", prompt: "I like designing reusable patterns, components, and rules that make future work faster and more consistent.", dimension: "systems", kind: "anchor", reverse: false, weights: { product: 1, ux: 1, interaction: 2, research: 0, technology: 3, humanFactors: 1, content: 2 } },
    { id: "q15", prompt: "If the existing design system component is a poor fit for the task, I would customize the experience instead of forcing consistency.", dimension: "systems", kind: "tradeoff", reverse: false, weights: { product: 0, ux: 2, interaction: 2, research: 0, technology: -2, humanFactors: 1, content: 0 } },
    { id: "q16", prompt: "Before others reuse a pattern, I want usage rules, accessibility notes, token behavior, naming, and edge cases documented.", dimension: "systems", kind: "anchor", reverse: false, weights: { product: 0, ux: 1, interaction: 1, research: 1, technology: 2, humanFactors: 3, content: 3 } },
    { id: "q17", prompt: "For an early demo, I care more about the product story landing than whether the components are reusable or fully consistent.", dimension: "systems", kind: "tradeoff", reverse: false, weights: { product: 2, ux: 0, interaction: 1, research: -1, technology: -1, humanFactors: -1, content: 1 } },
    { id: "q18", prompt: "I want enough implementation fluency to make design decisions that can realistically ship, not just look good in a design file.", dimension: "build", kind: "anchor", reverse: false, weights: { product: 1, ux: 1, interaction: 1, research: 0, technology: 3, humanFactors: 0, content: 0 } },
    { id: "q19", prompt: "For an executive or client review, I would rather bring a high-fidelity or code-backed prototype than a low-fidelity artifact designed mainly for discussion.", dimension: "build", kind: "tradeoff", reverse: false, weights: { product: 1, ux: -2, interaction: 2, research: -3, technology: 3, humanFactors: -1, content: -1 } },
    { id: "q20", prompt: "I prefer handoff, critique, and design direction over debugging responsive behavior, implementation bugs, or browser details.", dimension: "build", kind: "tradeoff", reverse: false, weights: { product: 0, ux: 1, interaction: -1, research: 1, technology: -3, humanFactors: 0, content: 1 } },
    { id: "q21", prompt: "I would prototype with realistic data, states, and constraints even if that exposes messy feasibility problems earlier.", dimension: "build", kind: "anchor", reverse: false, weights: { product: 1, ux: 0, interaction: 2, research: 0, technology: 3, humanFactors: 1, content: 0 } },
    { id: "q22", prompt: "I treat safety, accessibility, error prevention, recovery paths, and realistic user conditions as core design quality.", dimension: "humanFactors", kind: "anchor", reverse: false, weights: { product: 1, ux: 2, interaction: 0, research: 2, technology: 0, humanFactors: 3, content: 2 } },
    { id: "q23", prompt: "I would sacrifice some accessibility or edge-case coverage if that is what lets the team hit a critical demo date.", dimension: "humanFactors", kind: "tradeoff", reverse: false, weights: { product: 2, ux: -2, interaction: 1, research: -1, technology: 2, humanFactors: -3, content: -1 } },
    { id: "q24", prompt: "I like mapping users, tasks, environments, failure modes, training needs, and recovery paths before calling a design complete.", dimension: "humanFactors", kind: "anchor", reverse: false, weights: { product: 1, ux: 1, interaction: 0, research: 2, technology: 0, humanFactors: 3, content: 1 } },
    { id: "q25", prompt: "For a low-stakes consumer app or class project, I am fine testing live instead of fully modeling rare error paths first.", dimension: "humanFactors", kind: "tradeoff", reverse: false, weights: { product: 1, ux: -1, interaction: 1, research: -2, technology: 2, humanFactors: -3, content: 0 } },
    { id: "q26", prompt: "I see naming, labels, helper text, error messages, tone, and instructions as part of the design itself.", dimension: "content", kind: "anchor", reverse: false, weights: { product: 1, ux: 2, interaction: 0, research: 1, technology: 0, humanFactors: 2, content: 3 } },
    { id: "q27", prompt: "The flow and visuals should be mostly locked before spending much time on microcopy or content details.", dimension: "content", kind: "tradeoff", reverse: false, weights: { product: 0, ux: -2, interaction: 2, research: -1, technology: 1, humanFactors: -2, content: -3 } },
    { id: "q28", prompt: "When copy is unclear, I would change layout, hierarchy, or interaction structure instead of treating the words as a final polish pass.", dimension: "content", kind: "tradeoff", reverse: false, weights: { product: 1, ux: 2, interaction: -1, research: 1, technology: -1, humanFactors: 1, content: 3 } },
    { id: "q29", prompt: "I want my strongest portfolio project to show both the reasoning behind the decision and the quality of the final execution.", dimension: "strategy", kind: "anchor", reverse: false, weights: { product: 2, ux: 2, interaction: 2, research: 2, technology: 2, humanFactors: 2, content: 2 } },
    { id: "q30", prompt: "I like switching between research, flow design, interaction details, content clarity, systems reuse, and implementation constraints depending on the project risk.", dimension: "strategy", kind: "anchor", reverse: false, weights: { product: 2, ux: 2, interaction: 2, research: 2, technology: 2, humanFactors: 2, content: 2 } },
  ],
  scoringModel: {
    model: "centered-likert-bipolar-anchor-tradeoff",
    anchorScoreWeight: 0.6,
    tradeoffScoreWeight: 0.4,
    note: "Anchor items measure broad capability/interest; tradeoff items create archetype separation. Neutral is zero signal. Positive weights pull toward a role; negative weights pull away from a role.",
    answerTransform: "const centeredAnswer = (question.reverse ? 6 - answer : answer) - 3;",
    rawScore: "rawScores[typeId] += centeredAnswer * weight;",
    maxAbsScore: "maxAbsScores[typeId] += 2 * Math.abs(weight);",
    roundedProfileRule: "If role alignments are broadly high with a low spread, label the result as a rounded / multidisciplinary designer profile instead of forcing one narrow archetype.",
  },
  dimensionRoleMap: {
    strategy: ["product"],
    experienceDesign: ["ux", "interaction"],
    research: ["research"],
    systems: ["technology", "interaction", "ux", "content", "humanFactors", "product"],
    build: ["technology"],
    humanFactors: ["humanFactors"],
    content: ["content"],
  },
  tieBreakerLogic: {
    showSecondaryIfWithin: 5,
    showBlendedIfWithin: 3,
    blendPairs: [
      ["ux", "interaction"],
      ["product", "research"],
      ["research", "humanFactors"],
      ["ux", "content"],
      ["interaction", "technology"],
      ["technology", "product"],
      ["interaction", "content"],
      ["ux", "humanFactors"],
    ],
  },
  biasAndValidityNotes: [
    "This is a directional self-reflection tool, not a validated career diagnosis.",
    "Role titles overlap across companies, so adjacent roles should be shown as nearby paths rather than wrong answers.",
    "Use preference-based wording more than achievement-based wording so students with limited internships are not penalized.",
    "Keep reverse-scored items simple and few; avoid dense negations or trick wording.",
  ],
};
